[tool.ruff]
line-length = 150
indent-width = 4
exclude = [
    ".git",
    ".tox",
    ".venv",
    "venv",
    "node_modules",
    ".vscode",
    "build",
    "dist",
    ".pytest_cache",
    "__pycache__",
    "migrations",
]
target-version = "py313"

[tool.ruff.lint]
select = ["I", "E", "F", "B", "W", "UP"]
ignore = [
    "B017",
    "UP006",
    "UP035",
    "B904",
    "E203",
    "E501",
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
